spring.application.name=VetKI
server.port=${PORT:8081}

# Configuración de PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vetki_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Guatemala
spring.jpa.open-in-view=false

# Inicialización de BD y datos iniciales (Fase 5)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# Formato y zona horaria de JSON (Jackson)
spring.jackson.time-zone=America/Guatemala
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false

# Parámetros JWT
jwt.secret=${JWT_SECRET:VetKISecretKeyMustBeAtLeast256BitsLongForHMACSHA256SecureVeterinaria2026}
jwt.expiration=${JWT_EXPIRATION:86400000}
